version: "3"

services:
  ruby:
    image: solnic/dt-ruby:latest
    build:
      context: base/ruby
  cli:
    image: solnic/dt-cli:latest
    build:
      context: base/cli
    depends_on:
      - ruby
  runner-rubocop:
    image: solnic/dt-runner-rubocop:latest
    build:
      context: base/runner-rubocop
    depends_on:
      - cli
  action-rubocop:
    image: solnic/dt-action-rubocop:latest
    build:
      context: action-rubocop
    depends_on:
      - runner-rubocop
