version: "3"

services:
  ruby:
    image: solnic/ah-ruby:latest
    build:
      context: base/ruby
  runner-rubocop:
    image: solnic/ah-runner-rubocop:latest
    build:
      context: base/runner-rubocop
  action-rubocop:
    image: solnic/ah-action-rubocop:latest
    volumes:
      - .:/github/workspace
    build:
      context: action-rubocop
    depends_on:
      - runner-rubocop
