# action.yml
name: 'RuboCop'
description: 'Runs RuboCop'
inputs:
  path:
    description: 'Path to file(s)'
    required: true
    default: '/'
outputs:
  result_file:
    description: 'Result file'
runs:
  using: 'docker'
  image: 'docker://docker.pkg.github.com/solnic/dt-actions/action-rubocop:latest'
  args:
    - ${{ inputs.path }}
