# action.yml
name: 'RuboCop'
description: 'Runs RuboCop'
inputs:
  type:
    description: 'The type of cops that should be used'
    required: false
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - ${{ inputs.diff }}
