# action.yml
name: 'RuboCop'
description: 'Runs RuboCop'
inputs:
  type:
    description: 'The type of cops that should be used'
    required: true
  diff:
    description: 'A list of files that changed'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - ${{ inputs.diff }}
