on:
  repository_dispatch:
    types: [rubocop]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Run rubocop
      id: rubocop
      uses: solnic/dt-actions/rubocop@main
      with:
        path: 'tests/rubocop/hello.rb'
    - name: Store results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.rubocop.outputs.result_file }}
        path: ${{ steps.rubocop.outputs.result_file }}
