name: "Devtools"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  RuboCop:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Run rubocop
      id: rubocop
      uses: action-hero/actions/rubocop@test-rubocop
      with:
        path: 'tests/rubocop/hello.rb'
