name: "Action Hero: RuboCop"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run
      uses: action-hero/actions/rubocop@test-rubocop
