name: "RuboCop"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  diff:
    runs-on: ubuntu-latest
    name: Check diff
    outputs:
      files: ${{ steps.set_files.outputs.files }}
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Get git diff
      uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          **/*.rb
          **/*.rake
          Gemfile
          Rakefile
    - name: Set files
      id: set_files
      run: echo "::set-output name=files::$GIT_DIFF"

  run:
    runs-on: ubuntu-latest
    needs: diff
    if: needs.jobs.diff.outputs.files != ''
    name: (matrix && ${{ matrix.type }}) || 'Skipped'
    strategy:
      fail-fast: false
      matrix:
        type: ["Style", "Layout", "Naming", "Lint", "Metrics", "Security"]
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Check ${{ matrix.type }}
      uses: action-hero/actions/rubocop@main
      env:
        GIT_DIFF: ${{ needs.jobs.diff.outputs.files }}
      with:
        type: ${{ matrix.type }}
