name: "Action Hero: RuboCop"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Check changed and/or new files
      id: rubocop
      uses: action-hero/actions/rubocop@test-rubocop
