name: "RuboCop"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  diff:
    runs-on: ubuntu-latest
    name: Set up diff
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Get git diff
      uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          **/*.rb
          **/*.rake
          Gemfile
          Rakefile
    - name: Store
      run: echo $GIT_DIFF > diff.txt
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: diff
        path: diff.txt
  style:
    runs-on: ubuntu-latest
    needs: diff
    name: "Style"
    steps:
    - name: Download the diff artifact
      uses: actions/download-artifact@v2
      with:
        name: diff
        path: /tmp
    - name: Set diff
      id: diff
      run: echo "::set-output name=files::$(cat /tmp/diff.txt)"
    - name: Clone
      uses: actions/checkout@v2
      if: steps.diff.outputs.files != ''
    - name: Style
      if: steps.diff.outputs.files != ''
      uses: action-hero/actions/rubocop@main
      env:
        GIT_DIFF: ${{ steps.diff.outputs.files }}
      with:
        type: Style
  naming:
    runs-on: ubuntu-latest
    needs: diff
    name: "Naming"
    steps:
    - name: Download the diff artifact
      uses: actions/download-artifact@v2
      with:
        name: diff
        path: /tmp
    - name: Set diff
      id: diff
      run: echo "::set-output name=files::$(cat /tmp/diff.txt)"
    - name: Clone
      uses: actions/checkout@v2
      if: steps.diff.outputs.files != ''
    - name: Naming
      uses: action-hero/actions/rubocop@main
      if: steps.diff.outputs.files != ''
      env:
        GIT_DIFF: ${{ steps.diff.outputs.files }}
      with:
        type: Naming
